// swift-tools-version: 5.10

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "client",
    platforms: [
        .iOS("14.0")
    ],
    products: [
        .iOSApplication(
            name: "client",
            targets: ["AppModule"],
            bundleIdentifier: "github.yaochenfeng.client",
            teamIdentifier: "DVP3U56PW8",
            displayVersion: "1.0.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .leaf),
            accentColor: .presetColor(.pink),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .utilities
        )
    ],
    dependencies: [
        .package(path: "../BizBase")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "BizBase", package: "bizbase")
            ],
            path: "app"
        )
    ],
    swiftLanguageVersions: [.v5]
)