// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import AppleProductTypes
import PackageDescription

let package = Package(
    name: "client",
    platforms: [
        .iOS("14.0")
    ],
    products: [
        .iOSApplication(
            name: "client",
            targets: ["AppModule"],
            bundleIdentifier: "github.yaochenfeng.client",
            teamIdentifier: "DVP3U56PW8",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .bowl),
            accentColor: .presetColor(.blue),
            supportedDeviceFamilies: [
                .pad,
                .phone,
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad])),
            ]
        )
    ],
    dependencies: [
        .package(path: "../Libs/DFBase")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "DFBase", package: "dfbase")
            ],
            path: "."
        )
    ],
    swiftLanguageVersions: [.v5]
)
